### ISSUE TITLE
maxConcurrency variable declared globally

### ISSUE THREAD

**Issue by bigwheels490** [almost/through2-concurrent#10]
If one is using through2-concurrent across multiple modules at the same time in a node application, which each module defining its own level of maximum concurrency, the last one in wins.  That is, all the instances will use that level of max concurrency.  This is because the maxConcurrency variable is defined without the 'var' keyword causing it to be defined globally.

**Comment by almost** [comment]
Oh wow, that's embarrassing! I've fix it and also added a "use strict" declaration so that mistakes like that will cause an obvious error.
