### ISSUE TITLE
Event loop might block if callback not always async

### ISSUE THREAD

**Issue by nadrane** [almost/through2-concurrent#11]
I ran into a pretty insidious bug that has taken me days to unravel, and I wanted to share it for anyone else who runs into the same problem.

The crux of the issue is that `through2-concurrent` requires that it's callback function (the one you the user provides) always be asynchronous. Clearly this is not strictly required by the library, but If that callback is not always asynchronous, it's possible for the event loop to block.

Let me share my code:

```js
  return throughConcurrent.obj({ maxConcurrency: concurrency }, async function(
    domain,
    enc,
    done
  ) {
    try {
      const url = await frontierList.getNextUrlForDomain(domain);
      if (url) {
        this.push(url);
      }
    } catch (err) {
      console.error(err)
    }
    done();
  });
};
```

What happens is that when the done() function is invoked inside my callback, my callback is synchronously invoked with a domain. This is all fine, except If that domain also causes `frontierList.getNextUrlForDomain(domain)` to return immediately without performing an async operation, invoking done causes my callback is once again be invoked synchronously. What happens, then, is that sometimes I get into a pattern where maybe some percentage of async callbacks never finish because every subsequent value causes `frontierList.getNextUrlForDomain(domain)` to return immediately without performing an async operation. The event loop is quickly blocked, and my async operations never finish.

A workaround for this was pretty simple. I was already using a wrapping around `through-concurrent`, but I will only share the relevant parts here.

```js
function createThroughConcurrent(concurrency, callback) {
  const stream = throughConcurrent.obj({ maxConcurrency: concurrency }, function(
    domain,
    enc,
    done
  ) {
    setImmediate(() => {
      callback.call(this, domain, enc, done);
    });
  });
  return stream;
};
```

The idea is that we want to clear the event loop no matter what before invoking our callback. This code accomplishes that.

**Comment by almost** [comment]
Hi, thanks for sharing!

I don't think I'm following exactly what's going wrong, maybe because I'm not fully understanding what `frontierList.getNextUrlForDomain` does.  Could you possibly supply a minimal example of the failure?

Thanks!

**Comment by nadrane** [comment]
umm sure! I think I can do that

**Comment by nadrane** [comment]
This example is a bit contrived, but it works

```js
const throughConcurrent = require("through2-concurrent");
const fs = require("fs");
const { promisify } = require("util");
const split = require("split");

const writeFileAsync = promisify(fs.writeFile);

fs
  .createReadStream("infiniteList.txt")
  .pipe(split())
  .pipe(throughConcurrent.obj({ maxConcurrency: 5 }, async function(domain, enc, done) {
    try {
      console.log("invoking callback");
      const url = await sometimesAsyncFunction(domain);
      if (url) {
        this.push(url);
      }
    } catch (err) {
      console.error(err);
    }
    done();
  }));

let calledBefore = false;
async function sometimesAsyncFunction(domain) {
  if (calledBefore) {
    return "";
  }
  calledBefore = true;
  // This is a readFile in my code, but clearly I don't want to have to stub that out
  await writeFileAsync("123.txt", domain);
  console.log("async operation finished");
  const someUrl = "http://123.com";
  return someUrl;
}
```

[infiniteList.txt](https://github.com/almost/through2-concurrent/files/1920908/infiniteList.txt)

I've attached a file that is basically a list of domains. For this demonstration, it's quite small, but imagine it were infinite.

When you run the code, you will notice that `invoking callback` will display repeatedly until the list is depleted, and only after that point does `async operation finished` log. This is a clear indication that the event loop is blocked and becomes  a problem when the result of the async operation influences the readable stream (which is what's happening in my scenario (not shown above)).

I hope this code makes it more clear what I'm doing

**Comment by almost** [comment]
That's actually the result I'd expect from that code. That `writeFileAsync` takes a (relatively) long time so you'd expect all the other things to happen before that completes.

Now if you removed the `calledBefore` bit so `sometimesAsyncFunction` is actually doing something each time then the `maxConcurrency` of 5 is going to cause it to wait after the 5th call until one of them complete before continuing.

With larger infinitelist.txt this *is* still going to lock up but for a different reason. You're not doing anything with the output of the stream so eventually it's going to fill up the internal buffer (see highWaterMark setting). You need either pipe it into something else or add a `.on('data', function (data) {})`

**Comment by nadrane** [comment]
That's all completely fair. Let me propose a slightly different example. I've changed my readstream into a readable that counts forever. I've made sure to pipe my code in `/dev/null` so that we don't reach the `highWaterMark`

```js
const throughConcurrent = require("through2-concurrent");
const fs = require("fs");
const { promisify } = require("util");
const { Readable } = require("stream");

const writeFileAsync = promisify(fs.writeFile);

class InfiniteStream extends Readable {
  constructor() {
    super({ objectMode: true });
    this.count = 1;
  }
  _read() {
    this.push(this.count.toString());
    this.count++;
  }
}

const infiniteStream = new InfiniteStream();
infiniteStream
  .pipe(throughConcurrent.obj({ maxConcurrency: 5 }, async function(count, enc, done) {
    try {
      console.log("invoking callback ", count);
      const url = await sometimesAsyncFunction(count);
      if (url) {
        this.push(url);
      }
    } catch (err) {
      console.error(err);
    }
    done();
  }))
  .pipe(fs.createWriteStream("/dev/null"));

async function sometimesAsyncFunction(count) {
  if (count > 0) {
    return "";
  }
  // This is a readFile in my code, but clearly I don't want to have to stub that out
  await writeFileAsync("123.txt", count);
  console.log("async operation finished");
  const someUrl = "http://123.com";
  return someUrl;
}
```

You can pipe this program into grep and see that "async operation finished" never logs, even though the transform stream gets invoked over and over again. While writing to the file definitely takes a relatively long period of time, I would expect it to eventually finish.

**Comment by almost** [comment]
I can see that this example is going to lock up the JS thread forever, but that's because your InfiniteStream in synchronous and never exhausts. You could in this case fix it by putting a setImmediate in the through2-concurrent callback but I'd argue the correct place to do that would be the in the InfiniteSteam.

Here's a much simplified version of your previous example that illustrates what I mean:

```
const { Readable } = require("stream");

class InfiniteStream extends Readable {
  constructor() {
    super({ objectMode: true });
  }
  _read() {
    this.push('');
  }
}

(new InfiniteStream).on('data', function () {
});

setTimeout(function () {
  console.log("This never prints");
}, 1)
```

**Comment by nadrane** [comment]
ahhh, thank you

I always thought `_read` was invoked asynchronously. That explains a lot.

so does that mean that the callback to the `data` event is continuously pushed information, effectively invoking the `_read` over and over again, until the readable stream pushes `null` or until the writeable signals backpressure? And I imagine pipe does that exact same thing?

**Comment by almost** [comment]
Yes that should be what's happening. Usually in real world things there's something asynchronous somewhere in the chain that makes it ok even if the readable is infinite (or very large) but it's these edge cases that make for confusing debugging :)
